### ISSUE TITLE
Hi, any idea why I get this when trying mklivecd after updating my unity/mageia6

### ISSUE THREAD

**Issue by 0nlyHuman** [unity-linux/mklivecd#7]

**Comment by 0nlyHuman** [comment]
Creating initrd via dracut:                        [100.00% 00:00:45/00:00:45]
Creating grub2 boot menu:                          [ cp: target '/root/tmp/mklivecd.15831/livecd/boot/grub/' is not a directory     ]
DIE
FATAL: Execution of 'cp -rf /usr/lib/grub/* /root/tmp/mklivecd.15831/livecd/boot/grub/' failed
[root@unity-linux ~]#

**Comment by 0nlyHuman** [comment]
**Update:** looked at sbin/mklivecd, and changed line 597  from grub2 to grub
as that seemed to be what it was looking for, seems to be building now, though will have to wait to test out iso built to see if it boots.
(As previously mentioned, I copy boot/grub2 and rename grub, as otherwise doesn't work)

**Comment by jmiahman** [comment]
Please use the most current version, this has already been addressed

**Comment by unitylinux** [comment]
https://github.com/unity-linux/mklivecd/commit/cf8c05ec7d0a2c839db590c3f267cd080deda05e

**Comment by 0nlyHuman** [comment]
Asummed I had the latest as had done dnf update,
but looks like you no longer build for mageia6 only cauldron?
https://copr.fedorainfracloud.org/coprs/jmiahman/mklivecd/builds/
**update:**  Today, as you imply I am not using the latest mklivecd version I removed version mklivecd 0.9.7.8 then downloaded from copr manually version 0.9.7.8 built 3 hours ago (same version) result exactly the same, never mind I have a solution that works for me, thanks for your work.
Odd just tried latest mklivecd on another system a mageia 6 an it worked ok,
Maybe something it just doesn't like something on the unity linux iso based system I used.
Might delete it an start afresh using unity cauldron latest iso.

**Comment by 0nlyHuman** [comment]
Deleted unitylinux in vbox installed latest unity iso, doesn't boot up after installing, 
mentions unrecognised mount option lowerdir/var/lib/docker/overlay2   etc

**Comment by jmiahman** [comment]
Yeah the unity-iso just tests the functions of mklivecd, once it gets past dracut no guarantees. Looks like someone tried to make it smart.. ie detect a docker instance and it's now getting confused. You'll have better luck (sadly) on an install, how it's supposed to be used, versus using those as a base at this point. Maybe one day I can get something auto-building with docker that's usable, but I am tempted to switch to using nspawn anyway.. for that matter rework this whole format and do some actual legit testings and then actual legit builds that work and can be used for a desktop.. but I digress.

What's interesting is Magiea changed grub mid release.. I assumed you were mixed up trying to use cauldron with an old 6 release or visa versa. Project wise I was prepped for grub changes (bigger changes) to happen when 7 was released, not 6. I may have to start building for 6 again as well. The 6 rpms were working until it looks like they did some pretty major changes (to Grub), which normally would constitute a major release change. The link I posted above is the change on code from two months ago.. which fixed the issue in 7 (cauldron):
https://github.com/unity-linux/mklivecd/commit/cf8c05ec7d0a2c839db590c3f267cd080deda05e

The code has been fixed and you were using an older version.. or else you wouldn't see that error. The reason however was that I don't think those changes are in the 6 rpms as outlined by my obviously wrong assumption above that Mageia would not change grub, where it installs and it's behavior mid release (in a 6 release). So I'll have to look into getting the current version to build 6 rpms as well and see if that fixes it.

**Comment by 0nlyHuman** [comment]
I have been making iso's also in vbox mageia 6 which I don't think was from a unity installed iso, but now realise many remasters assumed were ok as only tried them as livecd's seem to have problem not being able to on installing with draklive-install write to new root, in terminal it mentions tar: /union: cannot open: no such file or directory.
(I notice on pclos livecd's they have a folder called union,  which is not on unity or mageia created iso's maybe they don't need it?)
If I reboot a livecd an put boot to verbose very early on it mentions booting the kernel switch root failed to unlink live:directory not empty, Failed to start Remount Boot and kernel file systems.
Maybe if I used an older kernel it might work.

**Comment by jmiahman** [comment]
I'm not seeing anything in the current code that would point to union? Are you sure you don't have something else installed? I'll make a bootable ISO and test just to make sure.

**Comment by jmiahman** [comment]
Okay to be completely honest here.. the grub thing may have been my fault.. a long time ago I pushed for grub(bios) and grub-efi to be installed side by side in Mageia. I think I even submitted a patch. Neal actually reminded me of this. Looks like that change got submitted and that may have lead to the grub changes overall. So my being a bit annoyed, at least some of that can be placed on me.. now I guess they back ported it to 6 because it is a needed feature, so.. I won't take all the blame, but ideally maybe a symlink or something could have been created for 6 to not break compat.. most likely though they didn't even think about outside projects depending on grub location because there's not to many for Mageia.. so.. yeah..

So I created an ISO, actually something got fixed.. and they started working again. I won't call them stable I did create a snapshot folder for my lxqt builds that I have tested to a point (in QEMU, VirtualBox 5.2.8 and on Dell XPS M1210). Connected to wifi watched videos on all while running live.. you can find that here:
http://unitylinux.com/pub/isos/lxqt-snapshots/

This is the first time with Mageia I have had a workable build from container, that hasn't locked up on my hardware constantly. 

Back to your question, in /usr/sbin/draklive-install on line 62 there's a variable that gets defined in a file /etc/sysconfig/draklive-install called "copy_source" by default I do not use this file.. so It's not in my images, however if it's in your images you can remove the file or the defined variable in the file and it should default to using / or the root of the file system to copy.

**Comment by 0nlyHuman** [comment]
Thanks downloaded iso, xdm  as usual never showed  ctrl+alt+F3 then login an startx got to desktop, it mentions booting the kernel switch root failed to unlink live:directory still.
I was able to use draklive-install to install, though at end it mentions error dependency missing draklive-install is needed by installed task-unity-lxqt-live.
The installed iso doesn't boot up,
here is boot screenshot of error booting installed system 
https://www.enlightenment.org/ss/e-5ac368826a0aa8.68318683.jpg

**Comment by jmiahman** [comment]
Yes it looks like the old initrd (generated in the docker during install)
is not being overwritten by draklive-install.. the draklive-install error
is due to it trying to uninstall itself and right now the live package has
a hard requires and not a suggest.. that's the least of my issues. I think
I have a fix for the initial issue, just have to test it.

**Comment by 0nlyHuman** [comment]
Latest iso 20180404 boots when installed  congrats and thanks, it looked like may have done something extra at end of installing.
(I noticed the iso when booting gave that switch unlink error still).

**Comment by 0nlyHuman** [comment]
I updated the mageia6 system I had installed, with latest mklivecd an a few other updates, it created the live iso but when trying to install complained unable to write to new root.

**Comment by jmiahman** [comment]
huh, can you give me the exact error?

**Comment by 0nlyHuman** [comment]
Maybe I was just unlucky could try again, says have 0.9.7.14 mga6 installed, I have kernel 4.14.30, could it be because it is mga6 an not mga7 it is of a vbox installed system I have had for sometime, can't remember it's orig but in /etc seems to indicate an official mga6 release, dracut ver installed says ver 044 rel 11.1mga6 draklive-install version installed is 2.14 rel 1mga6
Looking in software managr I did notice drakxtools-backend  had a blue padlock dunno if that could ffect anything says version 17.88.1 rel 1.mga6
This is a screenshot.
https://www.enlightenment.org/ss/e-5ac89fb599dc56.47081908.jpg

**Comment by jmiahman** [comment]
It's not that you're unlucky it's that you have a file in /etc/sysconfig or
the alike that's tell mklivecd to use /union are you coping something from
PCLinuxOS?

**Comment by jmiahman** [comment]
Maybe run a grep -H -r '/union' /etc and see what comes up.

**Comment by 0nlyHuman** [comment]
Thanks, nothing pclos far as aware,
this is the output of that command grep -H -r '/union' /etc
https://www.enlightenment.org/ss/e-5ac8ee1dcc2f35.95514298.jpg

**Comment by jmiahman** [comment]
? Either that image is really screwed up, and I would ditch it, or somehow your command is wrong? Either way grep should not be searching through proc in /etc.. there's something really screwed about about that. Maybe try it again.
`grep -H -r '/union' /etc/`

**Comment by 0nlyHuman** [comment]
I saw somewhere else they used a -R (uppercase output is different an mentions mkremaster
https://www.enlightenment.org/ss/e-5ac8fe7c08c3a8.71246344.jpg
tried what you just mentioned grep -H -r '/union' /etc/    
output now mentions draklive-install
https://www.enlightenment.org/ss/e-5ac8ffcb087ee4.40282056.jpg
Think will try deleting that file can't see it on unity iso
removed file on livecd an now is installing, thanks for help, suspect it may have been something left over from long ago that didn't get  removed through updating, so assuming related to  just this installed system.
iso installed :)

**Comment by jmiahman** [comment]
The fact you have anything with /union on this system means it's not from mageia 6 or that you've
modified something and are either not being completely honest or you just
have no clue. Looking over your first image.. I am wagering on, no clue.. and that's not your fault. Looks like you're trying to use mkremaster which hasn't been ported and needs to be rewritten as Mageia does not use /union as any mount point and mkremaster relies heavily on /union being present:

`overlay on / type overlay (rw,relatime,lowerdir=/live/distrib,upperdir=/live/tmpfs/memory,workdir=/live/tmpfs/work)`

However PCLinuxOS does and has modified draklive-install through an external variable to use /union instead of /.. as I outlined a few posts above.

**Comment by jmiahman** [comment]
@0nlyHuman  #8 Has been opened to address this issue.

**Comment by 0nlyHuman** [comment]
I have far as I am aware nothing pclos accept some enlightenment themes, I can't recall ever trying mkremaster, 
I searched mklivecd version 0.9.13 and can see echo "SOURCE=/union" > /etc/systemconf/draklive-install  mentioned in rc.sysinit  
Sorry if been a nuisance, (at least something has come out of it, mkremaster getting an update.)

**Comment by jmiahman** [comment]
In current version 9.7.15 we no longer use the old init system, so the file rc.sysinit is no longer used and have been removed. This was all deprecated when we moved to dracut, other (and older) versions of mklivecd, like mylivecd still use it. We haven't now for quite some time, since October..

https://github.com/unity-linux/mklivecd/commit/b58a8e3eb7b2f6cba461fd1660a6932962f8efa5

That was version 9.7.2 and that was built for Magiea 6, so If you're running the lastest version of mklivecd that file should not be created, maybe you used an older version at some point for testing? At this point there's been some pretty major changes so careful with that :)
